dist: xenial
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
install:
  - pip install coverage coveralls
script:
  - coverage erase
  - coverage run --source semidbm test_semidbm.py
notifications:
  email:
    - pankow.ben@gmail.com
after_success: coveralls
